### ISSUE TITLE
This mod causes freezing in other biomes while Moder has not been defeated.

### ISSUE THREAD

**Issue by thecybermind** [Turbero/valheim-BiomeConqueror#1]
The UpdateEnvironment hook is not updating properly, and players receive Freezing in other biomes when not wearing a wolf cape. Moder has not been defeated by anyone on this server yet.

Edit: you also fail to check for the Enabled or ModerBenefitEnabled settings in the hook, so this continues to happen even with the mod or feature disabled.

**Comment by Turbero** [comment]
Hi Thecybermind.

Thanks for your feedback.

There is no hook for UpdateEnvironment, only for Character.OnDeath and TextsDialog.AddActiveEffects. I think there is a misunderstanding with how you think the mod works. 

First of all, the mod doesn't erase the freezing effect or others before defeating the boss of that biome. You have to defeat the boss in other to receive the benefit. 

In the case of Moder:
- before defeating Moder the freezing effect in Mountains takes effect as usual
- after defeating Moder then the effect will disappear for you. It will be for everyone in the server if the option worldProgression is active in the config file (it is false by default).

The ModerBenefitEnabled and the others are only to decide which benefits will be available for your game once they are earned (by defeating their biome bosses). Enabling these checks do not guarantee the benefit, only it enables the option to earn them.

I hope this explanation helps you =) Let me know otherwise!

**Comment by thecybermind** [comment]
So the code in WeatherPatch.cs does nothing? 

Also, if it is not this mod causing it, there must be some weird interaction with another mod since removing this mod stopped the issue (players no longer receive Freezing in other biomes).

**Comment by Turbero** [comment]
Sorry I was to sleepy when I answered you. Of course there is UpdateEnvironment! 

WeatherPatch does something. It manages spawn and mountains.

When I have time next week I'll change configuration file variable names to make be more self explanatory and avoid confusion.

Thanks for your feedback again!
